

const pokemonData = [
    {
      id: '001',
      name: 'Bulbasaur',
      image: require('../assets/bulbasaur.png'),
      weakness: ['Fire', 'Flying', 'Ice', 'Psychic'],
      strength: ['Water', 'Electric', 'Grass'],
      breed: 'Seed Pokémon',
      height: '0.7 m',
      gender: 'Female / Male',
      weight: '6.9 kg',
      description: 'Bulbasaur is a small, squat Pokémon with a green body and darker green spots. It has red eyes, pointed ear-like structures on top of its head, and a plant bulb on its back that grows as it evolves. Often found in grassy areas, Bulbasaur is friendly and affectionate towards trainers.',
    },
    {
      id: '002',
      name: 'Ivysaur',
      image: require('../assets/ivysaur.png'),
      weakness: ['Fire', 'Flying', 'Ice', 'Psychic'],
      strength: ['Water', 'Electric', 'Grass'],
      breed: 'Seed Pokémon',
      height: '1.0 m',
      gender: 'Female / Male',
      weight: '13.0 kg',
      description: 'Ivysaur is the evolved form of Bulbasaur, characterized by a large flower bud on its back that is starting to bloom. It has a blue-green body and darker blue-green spots. Ivysaur can utilize stronger Grass-type moves and is more powerful than its pre-evolution.',
    },
    {
      id: '003',
      name: 'Venusaur',
      image: require('../assets/venusaur.png'),
      weakness: ['Fire', 'Flying', 'Ice', 'Psychic'],
      strength: ['Water', 'Electric', 'Grass'],
      breed: 'Seed Pokémon',
      height: '2.0 m',
      gender: 'Female / Male',
      weight: '100.0 kg',
      description: 'Venusaur features a massive, fully bloomed flower on its back, showcasing various colors depending on its health and environment. Known for its strength and nature control, Venusaur has a calm demeanor but can be fierce when threatened, utilizing its powerful vines and flower in battle.',
    },
    {
      id: '004',
      name: 'Charmander',
      image: require('../assets/charman.png'),
      weakness: ['Water', 'Ground', 'Rock'],
      strength: ['Bug', 'Steel', 'Grass'],
      breed: 'Flame Pokémon',
      height: '1.0 m',
      gender: 'Female / Male',
      weight: '8.5 kg',
      description: 'Charmander is a small, bipedal Pokémon with an orange body and a fiery tail. It is known for its strong will and determination. The flame at the tip of its tail indicates its health; when healthy, the flame burns brightly. Charmander is playful and fiercely loyal to its trainer.',
    },
    {
      id: '005',
      name: 'Charizard',
      image: require('../assets/charizar.png'),
      weakness: ['Water', 'Electric', 'Rock'],
      strength: ['Bug', 'Steel', 'Grass', 'Fairy'],
      breed: 'Flame Pokémon',
      height: '1.7 m',
      gender: 'Female / Male',
      weight: '90.5 kg',
      description: 'Charizard is a dragon-like Pokémon with large wings and a fiery tail. It can breathe intense flames and is known for its ferocious nature. Charizard is highly sought after by trainers for its powerful flying abilities and strength in battle, making it a formidable opponent.',
    },
    {
      id: '006',
      name: 'Squirtle',
      image: require('../assets/squirtle.png'),
      weakness: ['Electric', 'Grass'],
      strength: ['Fire', 'Ground', 'Rock'],
      breed: 'Tiny Turtle Pokémon',
      height: '0.5 m',
      gender: 'Female / Male',
      weight: '9.0 kg',
      description: 'Squirtle is a small, blue turtle Pokémon with a playful demeanor. Known for its powerful water-based attacks, Squirtle is often found near water bodies. It can withdraw into its shell to protect itself from danger. Squirtle is a popular choice for trainers due to its loyal nature.',
    },
    {
      id: '007',
      name: 'Wartortle',
      image: require('../assets/wartortle.png'),
      weakness: ['Electric', 'Grass'],
      strength: ['Fire', 'Ground', 'Rock'],
      breed: 'Turtle Pokémon',
      height: '1.0 m',
      gender: 'Female / Male',
      weight: '22.5 kg',
      description: 'Wartortle is the evolved form of Squirtle, featuring large ears and a fluffy tail. It is more agile than its pre-evolution and can perform powerful water attacks. Wartortle is known for its loyalty and playful nature, making it a favorite among trainers.',
    },
    {
      id: '008',
      name: 'Charmeleon',
      image: require('../assets/charmele.png'),
      weakness: ['Water', 'Ground', 'Rock'],
      strength: ['Bug', 'Steel', 'Grass'],
      breed: 'Flame Pokémon',
      height: '1.1 m',
      gender: 'Female / Male',
      weight: '19.0 kg',
      description: 'Charmeleon is the evolved form of Charmander, known for its aggressive nature. It has a long tail with a flame that burns brighter when it is excited. Charmeleon is known for its fiery temperament and strong will, often seeking battles to prove its strength.',
    },
  ];
  
  export default pokemonData;
  